spring:
  application:
    name: servidor-gateway   
  cloud: 
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*" 
      routes:
      - id: servClientes #Id de la ruta 
        uri: lb://servicio-clientes
        predicates:
          - Path=/sclientes/** #Cuando Gateway detecte que en la peticion URL venga este path, enrutara la peticion hacia el servicio indicado en la propiedad "uri" (lb://servicio-productos)
        filters:
          - RewritePath=/sclientes/*, / #Lo que indica es que a la url indicada en la propiedad "uri", se le adicionará un "/" mas todo lo que venga despues de "sproductos" en la petición URL de entrada        
      - id: servHotes
        uri: lb://servicio-hoteles 
        predicates:
          - Path=/shoteles/**
        filters:
          - RewritePath=/shoteles/*, / 
      - id: servVuelos
        uri: lb://servicio-vuelos 
        predicates:
          - Path=/svuelos/**
        filters:
          - RewritePath=/svuelos/*, /
      - id: servReservas
        uri: lb://servicio-reservas 
        predicates:
          - Path=/sreservas/**
        filters:
          - RewritePath=/sreservas/*, / 
server:
  port: 11000
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka